######################################################################
# Automatically generated by qmake (3.0) ?? ???. 29 15:45:12 2019
######################################################################

TEMPLATE = app
TARGET = MyClientXML
INCLUDEPATH += .

# Input
HEADERS += \
    myclientxml.h
SOURCES += main.cpp \
    myclientxml.cpp

QT += widgets\
      core\
      network\
      xml
CONFIG +=c++11
